<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.ralf</groupId>
	<artifactId>a-simple-alarm-clock</artifactId>
	<version>1.0-SNAPSHOT</version>
	<name>ASAC</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<javafx.version>23.0.2</javafx.version>
		<mainClass>com.ralf.asac.Asac</mainClass>
	</properties>

	<dependencies>

		<dependency>
			<groupId>io.github.classgraph</groupId>
			<artifactId>classgraph</artifactId>
			<version>4.8.184</version>
		</dependency>

	</dependencies>

	<profiles>

		<!-- Windows native libraries -->
		<profile>
			<id>windows</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<os>
					<family>windows</family>
				</os>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-graphics</artifactId>
					<version>${javafx.version}</version>
					<classifier>win</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-controls</artifactId>
					<version>${javafx.version}</version>
					<classifier>win</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-media</artifactId>
					<version>${javafx.version}</version>
					<classifier>win</classifier>
				</dependency>
			</dependencies>
		</profile>

		<profile>
			<id>linux</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<os>
					<family>unix</family>
					<name>Linux</name>
				</os>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-graphics</artifactId>
					<version>${javafx.version}</version>
					<classifier>linux</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-controls</artifactId>
					<version>${javafx.version}</version>
					<classifier>linux</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-media</artifactId>
					<version>${javafx.version}</version>
					<classifier>linux</classifier>
				</dependency>
			</dependencies>
		</profile>


		<!-- macOS native libraries -->
		<profile>
			<id>mac</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<os>
					<family>mac</family>
				</os>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-graphics</artifactId>
					<version>${javafx.version}</version>
					<classifier>mac</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-controls</artifactId>
					<version>${javafx.version}</version>
					<classifier>mac</classifier>
				</dependency>
				<dependency>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-media</artifactId>
					<version>${javafx.version}</version>
					<classifier>mac</classifier>
				</dependency>
			</dependencies>
		</profile>


	</profiles>

	<build>
		<plugins>
			<!-- Compiler -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>17</release>
				</configuration>
			</plugin>

			<!-- Shade Plugin: Fat-JAR -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>${mainClass}</mainClass>
									<manifestEntries>
										<Enable-Native-Access>ALL-UNNAMED</Enable-Native-Access>
									</manifestEntries>
								</transformer>
							</transformers>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>module-info.class</exclude>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
							<createDependencyReducedPom>false</createDependencyReducedPom>
						</configuration>
					</execution>
				</executions>
			</plugin>


			<plugin>
				<groupId>com.akathist.maven.plugins.launch4j</groupId>
				<artifactId>launch4j-maven-plugin</artifactId>
				<version>2.4.1</version>
				<executions>
					<execution>
						<id>l4j-clui</id>
						<phase>package</phase>
						<goals>
							<goal>launch4j</goal>
						</goals>
						<configuration>
							<headerType>gui</headerType>
							<jar>
								${project.build.directory}/${project.artifactId}-${project.version}.jar</jar>
							<outfile>${project.build.directory}/asac.exe</outfile>
							<downloadUrl>http://java.com/download</downloadUrl>
							<classPath>
								<mainClass>com.ralf.asac.Asac</mainClass>
								<addDependencies>false</addDependencies>
								<preCp>anything</preCp>
							</classPath>
							<icon>${project.basedir}/src/main/resources/asac.ico</icon>
							<jre>
								<!--	<path>${java.home}\bin</path>	-->			<!-- Version 1 -->
								<path>%JAVA_HOME%\bin</path> 	<!-- Version 2 -->
							</jre>
							<versionInfo>
								<fileVersion>1.0.0.0</fileVersion>
								<txtFileVersion>${project.version}</txtFileVersion>
								<fileDescription>A simple alarm clock</fileDescription>
								<copyright>2026 Ralf</copyright>
								<productVersion>1.0.0.0</productVersion>
								<txtProductVersion>1.0.0.0</txtProductVersion>
								<productName>${project.name}</productName>
								<companyName>Ralf</companyName>
								<internalName>Asac</internalName>
								<originalFilename>Asac.exe</originalFilename>
							</versionInfo>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>